query GetArticleBySlugQuery($slug: String!) {
    articleCollection(where: { slug: $slug }, limit: 1) {
        items {
            title
            slug
            thumbnail {
                url
                description
                width
                height
            }
            description
            body {
                json
                links {
                    assets {
                        block {
                            sys {
                                id
                            }
                            contentType
                            url
                            title
                            width
                            height
                            description
                        }
                    }
                }
            }
            keywords
            sys {
                publishedAt
            }
        }
    }
}
